const {  generateTextureImgFromPrompt, textToImage, generateTexturesFromPrompts, textToImageOpneAi, characterCreationOptionPrompt} = require("./api.js");

async function main() {
    // const texturePrompts = [
    //     `Card texture: Inspired by the Nordic sagas and the ambiance of The Witcher series, cool steel grays contrast with deep crimson stains. Ancient runic patterns glow faintly, like long-forgotten prophecies, with touches of worn leather in the corners. The texture embodies a sense of melancholy and valiance, with a finely-grained, parchment-like surface, exuding archetypal warrior grit, 8k, ArtStation winner`
    // ];
    // const boo = await textToImage(texturePrompts[0]);
    // console.log(boo); // This will print the mock value "Texture Image Path"
    const prompt1 = `I admit it, seeing the dark woods for the first time was scary. but after the first time I came there with my friends, I got connected to the forest so deep that I came there every day after school. Dried leaves rustled underfoot as I followed a flattened path deeper each day.
    after a few days of getting deeper following the path I spotted A deserted mansion Finger-traced dust unveiled '1902' etched into the cornerstone. I started running towards my house to call my friends but I tripped and fell. And when I woke up I was in the cabin in the middle of the forest and I tried to get up but I couldn't because of a sharp pain in my leg A myriad of footprints, all leading to a rickety wooden desk. Suddenly, I heard the door creak, and opening and an old man stepped in. He went to the desk and he took something not ordinary from there. and told me: "Oh finally, you woke up!". Splattered with leeching ink, a parchment map unfurled, held by his gnarled arthritis-ridden hands. "I need you to help me  you're stronger. I wanna know what's behind the waterfall ridge. I need it for my map".`
    // const res = await generateTexturesFromPrompts(prompt1)
    console.log('asdf')

    // const prompt = `Create a full-frame illustration for the front side of a virtual RPG character creation card. The card, titled 'A Wisp Lantern' in Noto Sans font. (and this is the ONLY readable text in this illustration) please create this front full frame illustration out of this description: "llustration': 'Bathed in soft, icy blue light, the lantern feels alive, its texture reminiscent of the crystalline formation of frost. The wisp trapped inside dances like a flickering flame, casting long, intricate shadows over the wind-etched silver and sapphire backdrop, adding to the mysterious undertones of the RPG world.' and also reference this: "An ethereal lantern, seemingly made from the chill of the mountaintop itself. Within its crystal-clear enclosure, a blue wisp flickers restlessly, providing a reclusive yet unwavering light, likely to come handy when navigating through the darkness.". The design should fill the entire frame. No additional text besides the title.
    // the back side of the card is generated by this prompt: "Card texture: Channeling the haunting beauty of Art Nouveau entwined with the chilling mystique of Siberian folklore, envision a backdrop swirling with icy blues and silvers. The edges of the card give the impression of frost creeping in, while delicate filigree designs, reminiscent of icicles, drape from the top and bottom. Central to this is an archetypal emblem of a mountain, surrounded by flourishes that suggest gusts of wind and snow. The design encapsulates the cold, mysterious aura of the Bear's Fang Summit and the secrets of the Ancient Lighthouse, all in an RPG essence."". I want the front side to have the same artistic influences and theme. the use of embellishments etc.
    // Remember, the design should fill the WHOLE frame. it's a full frame illustration!! make it epic.  size 1024X1024. artStation winner. cinematic. inspiring and inviting to discover a hero through the process of choosing cards. make it a bit rough, grainy, cinematic, impressionistic. RPG core game book alternative nische award winning. one time. collector's only. remember the only VISIBLE READABLE TEXT SHOULD BE THE TITLE: "A Wisp Lantern"`
    // const res2 = await textToImageOpneAi(prompt, 1, "/Users/shlomo.chotzen/Documents/GitHub/game/storyteller_be/assets/characterCreation/1.png")  
    // console.log(res2)

    const cardStat = {'title':'Swordsmanship',
     'description':'Flurries of snow dance around as you wield your sword, its edge slicing through the frozen air. Each swing of your weapon leaves a shimmering arc in its wake, a testament to your deftness and precision.',
     'category':'Skill', 
     'subcategory':'Combat', 
     'illustration': 'In the frosty realm of the card, your silhouette dances in smooth, fluid movements obstructed by the icy blue white of the surroundings. The ethereal glow of your sword illuminates the sapphire tinge of the whirling snowflakes, mirroring the challenges you have yet to face in this RPG universe.', 
     'font':'Noto Sans'
    }
    const cardPrompt = characterCreationOptionPrompt(cardStat);
    console.log('ss')
}



// Run the main function
main().catch(error => {
    console.error('Error:', error);
});